<template>
    <v-app>
        <HeaderDiscuss-component></HeaderDiscuss-component>
        <v-container>
            <DiscussChart-component></DiscussChart-component>
            <DiscussPost-component></DiscussPost-component>  
        </v-container>      
    </v-app>
</template>
