<template>
    <v-app>
        <HeaderDiscuss-component></HeaderDiscuss-component>
        <DiscussSidebar-component></DiscussSidebar-component>
        <v-main>
            <DiscussChart-component></DiscussChart-component>
            <DiscussPost-component></DiscussPost-component>  
        </v-main>
    </v-app>
</template>
